User interface
men32z/tic-tac-toe pull request #2
Opened 2019-10-09 17:07 UTC by men32z

2019-10-10 07:02 UTC, maelfosso requested changes
Hello @men32z @jstiven01 ,

Nice job done :clap: 
However, there is still some things to add to make it approved.

1. You should inform whether the move is valid or not
2. You should not only display the board at the beginning but after at each move
3. You should inform the user if it's a winning move or a draw one
4. Loop until one player win.

**OPTIONAL**
1. Ask the player name

All those steps without the logic, only the mock up.

Kindly make those changes and submit a new code review request.
Thanks

2019-10-11 15:56 UTC, men32z commented
> 
> 
> Hello @men32z @jstiven01 ,
> 
> Nice job done 👏
> However, there is still some things to add to make it approved.
> 
>     1. You should inform whether the move is valid or not
> 
>     2. You should not only display the board at the beginning but after at each move
> 
>     3. You should inform the user if it's a winning move or a draw one
> 
>     4. Loop until one player win.
> 
> 
> **OPTIONAL**
> 
>     1. Ask the player name
> 
> 
> All those steps without the logic, only the mock up.
> 
> Kindly make those changes and submit a new code review request.
> Thanks

Thanks for the review, we already did the changes, just the third one we think is part of the next task, Game Logic. Regards

2019-10-12 04:38 UTC, Ispirett requested changes
Great work so far @men32z @jstiven01 you are doing great.

There are some a bug to fix :bug: 

- [ ]  You should write a validator method that returns a message informing the player of incorrect input.

- [ ]  The game should show who's turn it is.

2019-10-12 15:40 UTC, men32z commented
> 
> 
> Great work so far @men32z @jstiven01 you are doing great.
> 
> There are some a bug d fix 🐛
> 
>     * [ ]   You should write a validator method that returns a message informing the player of incorrect input.
> 
>     * [ ]   The game should show who's it is.

@Ispirett  thanks for the comments but you should take a look again, this is User Interface task not the Game Logic. the project description is here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/ . and also the first point is actually working. the second one is not clear

2019-10-13 08:00 UTC, bolah2009 requested changes
Hi team :wave:

That been said, let's check the comments below. The missing parts of this milestone is taged with the :recycle: emoji. Let's address that, also, using comments is totally okay. :+1: 

#### :recycle:  Make these changes and submit another code review request. :+1: 

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2019-10-13 08:00 UTC, bolah2009 commented on bin/main.rb
> +puts "What is your name? (player O)"
:heavy_check_mark:  [OPTIONAL] game ask players for their names.

2019-10-13 08:00 UTC, bolah2009 commented on bin/main.rb
> +  puts "Pick a number to set the turn 'X' "
:recycle:  `[REQUIRED]` game tells which player turn it is

Could we at least add a comment to say this statement will change from `X` to `O` for the next player turn? :thinking:

Or something like this:
```suggestion
  player_turn = (there_turns % 2).zero? ? 'O' : 'X'
  puts "Pick a number player #{player_turn}"
```

or
```suggestion
  player_turn = (there_turns % 2).zero? ? player_o : player_x
  puts "Pick a number #{player_turn}"
```

It can also be a comment as I said earlier, it doesn't have to work. The point is to explain know how the game flow will work.

2019-10-13 08:00 UTC, bolah2009 commented on bin/main.rb
> +  puts move ? "your move is valid" : "your move is not valid"
:recycle: `[REQUIRED]` game asks player to select from available moves
:recycle: `[REQUIRED]` game informs player if selected move is invalid

Let's add a comment to handle invalid moves. 
What happens next when the move is invalid? WIll the game stop? Will the game ask for another move?
These are obvious questions but we need to indicate it since it's an important part of the game flow.

2019-10-13 08:00 UTC, bolah2009 commented on bin/main.rb
> +  puts " 7 | 8 | 9 "
:heavy_check_mark: `[REQUIRED]` game displays board after player move

2019-10-13 08:00 UTC, bolah2009 commented on bin/main.rb
> +puts "*************************"
:recycle:  `[REQUIRED]` game informs player if selected move is a winning move
:recycle:  `[REQUIRED]` game informs player if selected move is a draw move

Let's move these lines inside the loop and add comments for when it is a draw and use these when it is a win. Note that `there_turns` will be equal to zero when there's a win so that the loop can stop. Ideally, when `there_turns` is 0 then it is a draw.

2019-10-15 01:39 UTC, Ispirett approved these changes
Good job folks :+1:  :+1: 
Please don't forget the readme file as you progress
Please write descriptive commit and pull request messages in feature projects.

2019-10-15 15:13 UTC, merged